name: mqtt_client_example
description: Demonstrates how to use mqtt_client with Flutter.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mqtt_client: ^10.6.0
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
